import {summarize} from './model.mjs';
let data,view='progress';const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usd=n=>n==null?'Not recorded':'$'+n.toLocaleString('en-US',{maximumFractionDigits:2});
const badge=(s,c='')=>'<span class="badge '+c+'">'+esc(s)+'</span>';
const metric=(l,v,n,e=false)=>'<div class="metric '+(e?'emphasis':'')+'"><div class="metric-label">'+l+'</div><div class="metric-value">'+v+'</div><div class="metric-note">'+n+'</div></div>';
const translations={Preparing:'Preparing',Signed:'Signed','Under Execution':'Under execution',Completed:'Completed',Canceled:'Canceled',Drafting:'Drafting','Under Reviewing':'Under review',Updating:'Updating',Approved:'Approved','Reviewed w comments':'Reviewed with comments','Under Production':'In production','Quality Checking':'Quality check',Rectifying:'Rectification',Urgent:'Urgent',High:'High',Normal:'Normal',Low:'Low'};
const tr=s=>translations[s]||s||'Not recorded';
const panel=(t,s,b)=>'<section class="panel"><div class="panel-head"><h2>'+t+'</h2><span>'+s+'</span></div>'+b+'</section>';
const rowLink=r=>data.sourceUrl.replace(/#.*$/,'')+'#gid=1353027088&range=A'+r.sourceRow+':T'+r.sourceRow;
const datestr=t=>new Date(t).toLocaleString('en-US',{timeZone:'Asia/Shanghai',hour12:false,year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const day=()=>new Date(data.fetchedAt).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
const fields={amount:'Quote',paid:'Paid',contract:'Contract',drawing:'Drawings',production:'Production',paymentStage:'Payment stage',nextAction:'Next action',shipping:'Est. ship',arrival:'Est. arrival',actualArrival:'Actual arrival',logistics:'Shipping cost'};
function filtered(){return data.latest.filter(r=>!r.excluded&&(!$('#project').value||r.project===$('#project').value)).filter(r=>$('#scope').value==='all'||($('#scope').value==='urgent'&&r.urgent)||($('#scope').value==='missing'&&r.paid===null)||($('#scope').value==='review'&&!r.included));}
const projects=rows=>[...new Set(rows.map(r=>r.project))];
function actionDescription(r){
 if(r.actualArrival)return 'Arrived on '+r.actualArrival+'. Check whether the source priority and next action should be updated.';
 if(r.production==='Rectifying')return 'Rectification is in progress. Confirm completion and reinspection dates.';
 if(r.actionDue&&r.actionDue<day())return 'Action is past its due date of '+r.actionDue+'. Confirm current progress.';
 if(r.arrival&&r.arrival<day())return 'Expected arrival '+r.arrival+' has passed; actual arrival is not recorded.';
 return r.nextAction||'Record the next action and its due date.';
}
function attention(rows){
 const order={Urgent:0,High:1,Normal:2,Low:3};
 const list=rows.filter(r=>r.urgent||r.priority==='High'||(r.actionDue&&r.actionDue<day())||(r.arrival&&r.arrival<day()&&!r.actualArrival)).sort((a,b)=>(order[a.priority]??4)-(order[b.priority]??4));
 return panel('Critical actions',list.length+' items · Missing dates do not imply overdue','<div class="panel-body">'+(list.length?list.map(r=>'<div class="action"><div class="action-top"><strong>'+esc(r.project)+'</strong>'+badge(tr(r.priority),r.urgent?'red':'amber')+'</div><small>'+esc(r.item)+' · '+esc(r.supplier.replace(/\n/g,' / '))+'</small><p>'+esc(actionDescription(r))+'</p><small>Owner: '+esc(r.owner||'Not recorded')+' | Due: '+esc(r.actionDue||'Not recorded')+'</small></div>').join(''):'<p class="muted">No urgent or high-priority items identified in this selection.</p>')+'</div>');
}
function stages(rows){
 const names=['Quote / Contracting','Contract execution','Shop drawings','Drawings approved','In production','Rectification','Awaiting shipment / arrival','Arrived'];
 const max=Math.max(1,...names.map(n=>rows.filter(r=>r.stage===n).length));
 return panel('Procurement stages','One count per purchase item','<div class="panel-body">'+names.map(n=>{const count=rows.filter(r=>r.stage===n).length;return '<div class="bar-row"><span>'+esc(n)+'</span><div class="bar-track"><div class="bar-fill" style="width:'+count/max*100+'%;'+(n==='Rectification'?'background:#b73045':'')+'"></div></div><strong class="num">'+count+'</strong></div>';}).join('')+'<p class="section-note" style="margin-top:20px">Derived from arrival, production, drawings and contract fields. An item is not marked in transit without actual shipment evidence.</p></div>');
}
function detailItem(r){
 return '<div class="detail-item"><div class="detail-title"><div><h3>'+esc(r.item)+' '+badge(r.stage,r.urgent?'red':'blue')+'</h3><span class="muted">'+esc(r.supplier.replace(/\n/g,' / '))+' · '+esc(r.version)+' · '+esc(r.date||r.dateRaw)+'</span></div><a href="'+esc(rowLink(r))+'" target="_blank" rel="noopener">Source row '+r.sourceRow+' ↗</a></div><div class="mini-grid"><div><small>Product quote'+(!r.included?' · Excluded':'')+'</small><strong>'+esc(r.amount===null?r.amountRaw:usd(r.amount))+'</strong></div><div><small>Contract</small><strong>'+esc(tr(r.contract))+'</strong></div><div><small>Drawings</small><strong>'+esc(tr(r.drawing))+'</strong></div><div><small>Production</small><strong>'+esc(tr(r.production))+'</strong></div></div><p><strong>Next action: </strong>'+esc(r.nextAction||'Not recorded')+'</p><div class="date-list"><span>Est. ship <strong>'+esc(r.shipping||'Not recorded')+'</strong></span><span>Est. arrival <strong>'+esc(r.arrival||'Not recorded')+'</strong></span><span>Actual arrival <strong>'+esc(r.actualArrival||'Not recorded')+'</strong></span></div>'+(r.notes.length?'<ul class="note-list">'+r.notes.map(n=>'<li>'+esc(n)+'</li>').join('')+'</ul>':'')+(r.historyCount?'<details><summary><span>Quote history · '+r.historyCount+' versions (excluded from totals)</span></summary><div class="table-wrap"><table><thead><tr><th>Version / Date</th><th>Supplier</th><th>Quote</th><th>Source</th></tr></thead><tbody>'+r.history.map(h=>'<tr><td>'+esc(h.version)+'<small>'+esc(h.date||h.dateRaw)+'</small></td><td>'+esc(h.supplier)+'</td><td>'+esc(h.amountRaw)+'</td><td><a href="'+esc(rowLink(h))+'" target="_blank" rel="noopener">Row '+h.sourceRow+' ↗</a></td></tr>').join('')+'</tbody></table></div></details>':'')+'</div>';
}
function details(rows){
 return panel('Project register',projects(rows).length+' projects · Expand for items and source records',projects(rows).map(p=>{const group=rows.filter(r=>r.project===p),s=summarize(group);return '<details><summary><strong>'+esc(p)+'</strong><span class="summary-meta">'+group.length+' items</span><span class="money">'+(s.unpriced===s.items?'Pending review':usd(s.amount))+'</span>'+(s.unpriced?badge(s.unpriced+' amounts under review','amber'):'')+'</summary><div class="detail-body">'+group.map(detailItem).join('')+'</div></details>';}).join(''));
}
function cashTable(rows){
 return panel('Cash flow by purchase item','Due now = max(cumulative target − paid, 0)','<div class="table-wrap"><table><thead><tr><th>Project / Item</th><th>Latest quote</th><th>Paid to date</th><th>Payment stage</th><th>Cumulative target</th><th>Due now</th><th>Outstanding</th><th>Payment Due Date</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><a href="'+esc(rowLink(r))+'" target="_blank" rel="noopener"><strong>'+esc(r.project)+'</strong></a><small>'+esc(r.item)+'</small></td><td class="money">'+(r.included?usd(r.amount):badge('Amount pending review','amber'))+'<small>'+esc(r.version)+'</small></td><td class="money">'+usd(r.paid)+(r.paidSource?'<small>'+esc(r.paidSource)+'</small>':'')+'</td><td>'+(r.targetPct!==null?'Target: '+r.targetPct+'%':esc(r.paymentStage||'Not recorded'))+'</td><td class="money">'+usd(r.target)+'</td><td class="money">'+usd(r.currentDue)+'</td><td class="money">'+usd(r.remaining)+'</td><td>'+esc(r.paymentDue||'Not recorded')+'</td></tr>').join('')+'</tbody></table></div>');
}
function allocation(rows){
 const list=projects(rows).map(p=>({name:p,...summarize(rows.filter(r=>r.project===p))})).sort((a,b)=>b.amount-a.amount),max=Math.max(1,...list.map(p=>p.amount));
 return panel('Quote value by project','Included quotes · Unsigned included','<div class="panel-body allocation">'+list.map(p=>'<div class="bar-row"><span>'+esc(p.name)+'</span><div class="bar-track"><div class="bar-fill" style="width:'+p.amount/max*100+'%"></div></div><strong class="num">'+(p.unpriced===p.items?'Pending':usd(p.amount))+'</strong></div>').join('')+'</div>');
}
function funding(rows){
 const s=summarize(rows),known=rows.filter(r=>r.paymentDue&&r.currentDue!==null),start=Date.parse(day()+'T00:00:00Z');
 const sub=days=>known.filter(r=>Date.parse(r.paymentDue+'T00:00:00Z')>=start&&Date.parse(r.paymentDue+'T00:00:00Z')<=start+days*86400000).reduce((a,r)=>a+r.currentDue,0),full=known.length===rows.length;
 return panel('Funding readiness','Unknown payments are not zero','<div class="panel-body"><div class="mini-grid" style="grid-template-columns:1fr 1fr"><div><small>Cumulative target · '+s.targetKnown+' items</small><strong>'+(s.targetKnown?usd(s.target):'Not recorded')+'</strong></div><div><small>Payment data coverage</small><strong>'+s.paidKnown+' / '+s.items+' items</strong></div><div><small>Due in the next 14 days</small><strong>'+(full?usd(sub(14)):'Not recorded')+'</strong></div><div><small>Due in the next 30 days</small><strong>'+(full?usd(sub(30)):'Not recorded')+'</strong></div></div><p class="section-note">The cumulative target includes earlier amounts due. A target percentage without actual payments is insufficient to calculate the amount due now.</p><p class="section-note">Forecasts require a due date, a target and actual payments. Complete records: '+known.length+' / '+rows.length+' items.'+(!full&&known.length?'Known portion: 14 days '+usd(sub(14))+'; 30 days '+usd(sub(30))+'.':'')+'</p><p class="section-note">Freight is tracked separately and is not added to product quotes. Complete cash planning requires freight, taxes and other costs.</p></div>');
}
function reviews(rows){
 const list=rows.filter(r=>!r.included||r.notes.some(n=>/grouped|overlap|Version|exceeds|same quote date|attachment/i.test(n)));
 return panel('Quote reviews',list.length+' items','<div class="panel-body">'+(list.length?list.map(r=>'<div class="review-row"><strong>'+esc(r.project)+' · '+esc(r.item)+'</strong> '+badge(r.included?'Included / Review grouping':'Excluded for now','amber')+'<p>'+esc(r.amountRaw)+'</p>'+r.notes.filter(n=>!n.startsWith('Cumulative actual')).map(n=>'<p>'+esc(n)+'</p>').join('')+'</div>').join(''):'<p class="muted">No quote issues in the current selection.</p>')+'</div>');
}
function changes(){
 const list=data.changes.filter(r=>!$('#project').value||r.project===$('#project').value);
 return panel('Changes since last snapshot',data.previousAt?'Previous: '+datestr(data.previousAt):'Initial baseline','<div class="panel-body">'+(!data.previousAt?'<p class="muted">This is the first baseline. Future updates will show changes to quotes, payments and key milestones.</p>':!list.length?'<p class="muted">No field changes for the selected project in this snapshot.</p>':list.map(r=>'<div class="review-row"><strong>'+esc(r.project)+' · '+esc(r.item)+'</strong> '+badge(r.kind,'blue')+r.fields.map(f=>'<p>'+esc(fields[f.key]||f.key)+'：'+esc(f.before??'Not recorded')+' → '+esc(f.after??'Not recorded')+'</p>').join('')+'</div>').join(''))+'</div>');
}
function methods(){
 return '<section class="panel"><details><summary><strong>Definitions & maintenance</strong><span class="summary-meta">Maintain data in the source sheet</span></summary><div class="detail-body method"><p><strong>Latest quotes: </strong>The latest quote date is used for each project and purchase item, rather than relying only on version numbers. Historical quotes are retained. Canceled items are excluded. Potential change orders and multiple price options are listed separately. Supplier changes and aliases are explained in item notes.</p><p><strong>Payments & outstanding: </strong>Maintain cumulative actual payments in the source Paid column. Enter 0 only when no payment is confirmed; leave unknown amounts blank. Explicit text such as USD 5000 Paid is also recognized. Outstanding product value equals the latest included quote minus actual payments. Changes in quotes affect this balance.</p><p><strong>Payment stages: </strong>Pay-to 60% means the current cumulative payment target is 60%; it does not mean this has been paid. Target = latest quote × target percentage. Due now = max(target − paid, 0). The source To be Paid value is not used to infer actual payments.</p><p><strong>Dates & owners: </strong>For payment forecasts, add a Payment Due Date column to the source. For actions, add Owner and Next Action Due. Place these columns to the right of existing fields; they will be read on the next update. Quote dates are not progress-update dates.</p><p><strong>Currency & scope: </strong>'+esc(data.currencyNote)+'  Product quotes are EXW and exclude shipping, taxes and other costs. Recorded shipping costs are kept separately and are not included in the product subtotal. Unsigned quotes represent purchase budgets, not contractual liabilities.</p><p><strong>Scheduled updates: </strong>Both dashboards are refreshed and published to GitHub Pages every Monday and Thursday at 09:00 Beijing time. The last successful snapshot stays available if an update fails. The local Codex scheduled task needs this computer powered on, online and the app running.</p><p><strong>Source records: </strong>This snapshot reads '+data.sourceRows+' quote rows, with '+data.historyRows+' historical versions; canceled items: '+data.latest.filter(r=>r.excluded).length+' items. Missing actuals are not estimated.</p><a href="'+esc(data.sourceUrl)+'" target="_blank" rel="noopener">Maintain Google Sheets data ↗</a></div></details></section>';
}
function render(){
 const rows=filtered(),s=summarize(rows);$('#scope-count').textContent=s.projects+' projects · '+s.items+' purchase items';
 if(!rows.length){$('#app').innerHTML='<div class="empty">No matching purchase items. Choose another project or focus.</div>'+methods();return;}
 const metrics=view==='progress'?metric('Projects',s.projects,'Current purchase items: '+s.items+' items',true)+metric('Urgent / Rectification',s.urgent,'Source priority and production status')+metric('Latest quotes · Included subtotal',(s.unpriced===s.items?'Pending review':usd(s.amount)),s.unpriced+' amounts under review')+metric('Missing payment records',s.paidUnknown,'Actual payments recorded: '+s.paidKnown+' items'):metric('Latest quotes · Included subtotal',(s.unpriced===s.items?'Pending review':usd(s.amount)),'Unsigned included · '+s.unpriced+' items under review',true)+metric(s.paidKnown===s.items?'Paid to date':'Known payments',(s.paidKnown?usd(s.paid):'Not recorded'),'Payment coverage: '+s.paidKnown+' / '+s.items+' items')+metric('Total outstanding',s.remainingKnown===s.items?usd(s.remaining):'Not recorded','Known portion: '+usd(s.remaining)+' · '+s.remainingKnown+' items')+metric('Total due now',s.dueKnown===s.items?usd(s.currentDue):'Not recorded',s.dueKnown?'Known portion: '+usd(s.currentDue):'Needs both target and actual payments');
 const warning=s.unpriced||s.paidUnknown?'<div class="alert">'+(s.unpriced?s.unpriced+' quote items are excluded pending review. The included subtotal is shown. ':'')+(s.paidUnknown?s.paidUnknown+' items have no actual payment record; total paid and outstanding amounts remain incomplete.':'')+'</div>':'';
 $('#app').innerHTML='<div class="metrics">'+metrics+'</div>'+warning+(view==='progress'?'<div class="two-col">'+attention(rows)+stages(rows)+'</div>'+details(rows)+changes():'<div class="two-col">'+funding(rows)+allocation(rows)+'</div>'+cashTable(rows)+reviews(rows))+methods();
 $('#app').innerHTML=$('#app').innerHTML.replace(/\b1 items\b/g,'1 item').replace(/\b1 amounts\b/g,'1 amount').replace(/\b1 projects\b/g,'1 project');
 $('#scope-count').textContent=$('#scope-count').textContent.replace(/\b1 projects\b/g,'1 project').replace(/\b1 purchase items\b/g,'1 purchase item');
}
function setView(name){if(!['progress','cash'].includes(name))throw new Error('Unknown dashboard');view=name;for(const n of ['progress','cash']){$('#'+n+'-tab').classList.toggle('active',n===name);$('#'+n+'-tab').setAttribute('aria-pressed',String(n===name));}render();}
try {
 const res=await fetch('data.json',{cache:'no-store'});if(!res.ok)throw new Error('Read failed');data=await res.json();
 $('#source').href=data.sourceUrl;$('#stamp').textContent='Snapshot · '+datestr(data.fetchedAt)+' (Beijing time)';
 const stale=Date.now()-Date.parse(data.fetchedAt)>4*86400000;$('#freshness').textContent=stale?'Snapshot is over 4 days old. Check scheduled updates.':'Replaced after each successful update';if(stale)$('#freshness').classList.add('warn-text');
 $('#project').innerHTML+=[...new Set(data.latest.filter(r=>!r.excluded).map(r=>r.project))].sort().map(p=>'<option>'+esc(p)+'</option>').join('');
 $('#project').onchange=render;$('#scope').onchange=render;for(const n of ['progress','cash'])$('#'+n+'-tab').onclick=()=>setView(n);render();
 if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{await document.modelContext.registerTool({name:'show_procurement_dashboard',title:'Show project or cash flow dashboard',description:'Switch the visible dashboard and filter by project. Changes display only, not source data.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['progress','cash']},project:{type:'string'}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||!['progress','cash'].includes(input.view)||input.project!==undefined&&(typeof input.project!=='string'||input.project&&!data.latest.some(r=>!r.excluded&&r.project===input.project)))throw new Error('Invalid dashboard or project');$('#project').value=input.project||'';$('#scope').value='all';setView(input.view);return{view,project:$('#project').value||'All projects',summary:summarize(filtered()),snapshotAt:data.fetchedAt};}},{signal:lifecycle.signal});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{console.warn('Dashboard tools unavailable');}
 }
}catch(e){console.error(e);$('#app').innerHTML='<div class="alert">Dashboard data is temporarily unavailable. Please reopen later; source data is unchanged.</div>';}
